package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateRejectsNonEmptyTargetWithoutForce(t *testing.T) {
	target := t.TempDir()
	if err := os.WriteFile(filepath.Join(target, "exists.txt"), []byte("exists"), 0644); err != nil {
		t.Fatal(err)
	}

	err := Generate(Options{
		Type:     "api",
		Name:     "demo-api",
		Module:   "github.com/tiamxu/demo-api",
		Target:   target,
		SkipTidy: true,
		SkipTest: true,
	})
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestGenerateCreatesGoAPIProject(t *testing.T) {
	target := filepath.Join(t.TempDir(), "demo-api")

	err := Generate(Options{
		Type:     "api",
		Name:     "demo-api",
		Module:   "github.com/tiamxu/demo-api",
		Target:   target,
		SkipTidy: true,
		SkipTest: true,
	})
	if err != nil {
		t.Fatal(err)
	}

	files := []string{
		"AGENTS.md",
		"CLAUDE.md",
		"README.md",
		"doc/项目开发规范.md",
		"doc/设计文档.md",
		"doc/接口文档.md",
		"api/common.go",
		"config/config.go",
		"config/config.yaml",
		"routes/routes.go",
		"pkg/e/code.go",
		"main.go",
		"go.mod",
	}

	for _, file := range files {
		if _, err := os.Stat(filepath.Join(target, filepath.FromSlash(file))); err != nil {
			t.Fatalf("expected file %s: %v", file, err)
		}
	}

	goMod, err := os.ReadFile(filepath.Join(target, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(goMod), "module github.com/tiamxu/demo-api") {
		t.Fatal("go.mod module was not rendered")
	}

	readme, err := os.ReadFile(filepath.Join(target, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(readme), "demo-api") {
		t.Fatal("README project name was not rendered")
	}

	mainGo, err := os.ReadFile(filepath.Join(target, "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(mainGo), "repo.Init") || strings.Contains(string(mainGo), "cfg.DB") {
		t.Fatal("main.go should not initialize database by default")
	}

	configYAML, err := os.ReadFile(filepath.Join(target, "config", "config.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(configYAML), "db:") {
		t.Fatal("config.yaml should not contain database config by default")
	}

	manifestData, err := os.ReadFile(filepath.Join(target, ".gogen", "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var manifest Manifest
	if err := json.Unmarshal(manifestData, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest.ProjectType != "api" {
		t.Fatalf("unexpected project type %q", manifest.ProjectType)
	}
	if manifest.Module != "github.com/tiamxu/demo-api" {
		t.Fatalf("unexpected module %q", manifest.Module)
	}
	if !containsString(manifest.Files, "go.mod") {
		t.Fatal("manifest should contain go.mod")
	}
	if !containsString(manifest.Files, "config/config.yaml") {
		t.Fatal("manifest should contain config file")
	}
	if containsString(manifest.Files, "repo/init.go") {
		t.Fatal("manifest should not contain repo/init.go by default")
	}
	if _, err := os.Stat(filepath.Join(target, "repo", "init.go")); !os.IsNotExist(err) {
		t.Fatal("repo/init.go should not be generated by default")
	}

	withDBTarget := filepath.Join(t.TempDir(), "demo-api-with-db")
	if err := Generate(Options{
		Type:     "api",
		Name:     "demo-api",
		Module:   "github.com/tiamxu/demo-api",
		Target:   withDBTarget,
		WithDB:   true,
		SkipTidy: true,
		SkipTest: true,
	}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(withDBTarget, "repo", "init.go")); err != nil {
		t.Fatalf("expected repo/init.go with --with-db: %v", err)
	}
	withDBMain, err := os.ReadFile(filepath.Join(withDBTarget, "main.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(withDBMain), "repo.Init(&cfg.DB)") {
		t.Fatal("main.go should initialize database with --with-db")
	}
	withDBConfig, err := os.ReadFile(filepath.Join(withDBTarget, "config", "config.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(withDBConfig), "db:") || strings.Contains(string(withDBConfig), "enabled:") {
		t.Fatal("config.yaml should contain database config without enabled when --with-db")
	}
}

func TestProjectFilesUseTemplateSuffixForRenderedFiles(t *testing.T) {
	files, err := projectFilesByType("api")
	if err != nil {
		t.Fatal(err)
	}

	var hasGoMod bool
	var hasConfigYAML bool
	for _, file := range files {
		switch file.SourcePath {
		case "go.mod.tmpl":
			hasGoMod = true
			if file.TargetPath != "go.mod" || !file.Render {
				t.Fatal("go.mod.tmpl should render to go.mod")
			}
		case "config/config.yaml.tmpl":
			hasConfigYAML = true
			if file.TargetPath != "config/config.yaml" || !file.Render {
				t.Fatal("config/config.yaml.tmpl should render to config/config.yaml")
			}
		}
	}
	if !hasGoMod {
		t.Fatal("expected go.mod.tmpl")
	}
	if !hasConfigYAML {
		t.Fatal("expected config/config.yaml")
	}
}

func TestTemplateSetResolvesAPIProject(t *testing.T) {
	set, err := templateSet("api")
	if err != nil {
		t.Fatal(err)
	}
	if set.Name != "api" {
		t.Fatalf("unexpected template set %q", set.Name)
	}
	if set.Root != "templates/api" {
		t.Fatalf("unexpected template root %q", set.Root)
	}
}

func TestGenerateDoesNotWriteLocalKitReplaceByDefault(t *testing.T) {
	target := filepath.Join(t.TempDir(), "demo-api")

	err := Generate(Options{
		Type:     "api",
		Name:     "demo-api",
		Module:   "github.com/tiamxu/demo-api",
		Target:   target,
		SkipTidy: true,
		SkipTest: true,
	})
	if err != nil {
		t.Fatal(err)
	}

	goMod, err := os.ReadFile(filepath.Join(target, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(goMod), "replace github.com/tiamxu/kit") {
		t.Fatal("go.mod should not contain local kit replace by default")
	}
}

func TestGenerateWritesLocalKitReplaceWhenEnabled(t *testing.T) {
	target := filepath.Join(t.TempDir(), "demo-api")

	err := Generate(Options{
		Type:            "api",
		Name:            "demo-api",
		Module:          "github.com/tiamxu/demo-api",
		Target:          target,
		LocalKitReplace: true,
		SkipTidy:        true,
		SkipTest:        true,
	})
	if err != nil {
		t.Fatal(err)
	}

	goMod, err := os.ReadFile(filepath.Join(target, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(goMod), "replace github.com/tiamxu/kit") {
		t.Fatal("go.mod should contain local kit replace when enabled")
	}
}

func TestGenerateRejectsKitRepoRootTargetEvenWithForce(t *testing.T) {
	target := t.TempDir()
	if err := os.WriteFile(filepath.Join(target, "go.mod"), []byte("module github.com/tiamxu/kit\n"), 0644); err != nil {
		t.Fatal(err)
	}

	err := Generate(Options{
		Type:     "api",
		Name:     "demo-api",
		Module:   "github.com/tiamxu/demo-api",
		Target:   target,
		Force:    true,
		SkipTidy: true,
		SkipTest: true,
	})
	if err == nil {
		t.Fatal("expected error")
	}
}

func containsString(items []string, target string) bool {
	for _, item := range items {
		if item == target {
			return true
		}
	}
	return false
}
